import type {} from '@deepseek-ai/dsh-client-ui-session/client';
import type { ConnectionHandle } from '@deepseek-ai/dsh-client-connection/client';
import type { SlotRegistry } from '@deepseek-ai/dsh-client-ui-renderer/client';
import type { Context } from '@deepseek-ai/cordis';
import type {} from '@deepseek-ai/dsh-client-connection/client';
import type {} from '@deepseek-ai/dsh-client-locale/client';
import type {} from '@deepseek-ai/dsh-api-session-controller/client';
import type {} from '@deepseek-ai/dsh-client-ui-sidebar-right/client';
import type {} from '@deepseek-ai/dsh-client-ui-slots';
export type ClientContext = Context & { connection: ConnectionHandle; slots: SlotRegistry };
